### ISSUE TITLE
12 errors

### ISSUE THREAD

**Issue by theoknock** [tidwall/Avios#2]
Doesn't work. Bunk repository.

**Comment by tidwall** [comment]
I'm sorry that you are having problems with the repo. Could you describe the errors?

**Comment by theoknock** [comment]
Improper use of UnsafeMutablePointer, which you use 12 times for an total of 12 errors.

James 408-685-4049

On Thu, Sep 15, 2016 at 6:10 AM -0700, "Josh Baker" notifications@github.com wrote:

I'm sorry that you are having problems with the repo. Could you describe the errors?

**Comment by tidwall** [comment]
Are you using Xcode 8 and swift/3.0?

**Comment by theoknock** [comment]
Yes

James 408-685-4049

On Thu, Sep 15, 2016 at 7:33 AM -0700, "Josh Baker" notifications@github.com wrote:

Are you using Xcode 8 and swift/3.0?

**Comment by tidwall** [comment]
Avios is not swift/3.0 compatible at this time.

**Comment by theoknock** [comment]
Are you going to post the code in another version, then? Because 2.0 doesn't work, either.
James 408-685-4049

On Sun, Sep 18, 2016 at 9:42 AM -0700, "Josh Baker" notifications@github.com wrote:

Avios is not swift/3.0 compatible at this time.

**Comment by tidwall** [comment]
I have no plans to update this project to swift 3 at this time. Perhaps in the future. 
I'd be more than happy to accept a PR if someone is so inclined to take on the work.

**Comment by theoknock** [comment]
No, I'm saying the posted version doesn't work, even 2.0.

James 408-685-4049

On Sun, Sep 18, 2016 at 2:51 PM -0700, "Josh Baker" notifications@github.com wrote:

I have no plans to update this project to swift 3 at this time. Perhaps in the future. 

I'd be more than happy to accept a PR if someone is so inclined to take on the work.

**Comment by theoknock** [comment]
Can you take and send a screen shot of your app running? Command-Option-3...

James 408-685-4049

On Sun, Sep 18, 2016 at 2:54 PM -0700, "James Bush" theoknock@gmail.com wrote:

No, I'm saying the posted version doesn't work, even 2.0.

James 408-685-4049

On Sun, Sep 18, 2016 at 2:51 PM -0700, "Josh Baker" notifications@github.com wrote:

I have no plans to update this project to swift 3 at this time. Perhaps in the future. 

I'd be more than happy to accept a PR if someone is so inclined to take on the work.

**Comment by tidwall** [comment]
Thanks for the feedback. I just verified that the framework builds in Xcode 7 and that it can be upgraded to swift 2.3 in Xcode 8.

![image](https://cloud.githubusercontent.com/assets/1156077/18619656/2ea301ec-7db7-11e6-9903-5213dbc2e90f.png)

**Comment by theoknock** [comment]
Okay, let's see what message I should get if the build is successful using 2.3. The screenshot you sent demonstrates the ability to make a choice, but not the consequences of actually making that choice.

James 408-685-4049

On Sun, Sep 18, 2016 at 3:48 PM -0700, "Josh Baker" notifications@github.com wrote:

Thanks for the feedback. I just verified that the framework builds in Xcode 7 and that it can be upgraded to swift 2.3 in Xcode 8.

**Comment by tidwall** [comment]
Sounds good. Good luck and if you have any further problems please open up a new issue and provide the error messages. Thanks.

**Comment by theoknock** [comment]
No, I mean _you_ send a screenshot of a successful build.

James 408-685-4049

On Sun, Sep 18, 2016 at 4:03 PM -0700, "Josh Baker" notifications@github.com wrote:

Sounds good. Good luck and if you have any further problems please open up a new issue and provide the error messages. Thanks.

**Comment by tidwall** [comment]
Sorry but I'm not sending screenshots of apps. 

If you are running into errors, please provide those errors and perhaps we can find a fix or a workaround. Thanks.

**Comment by theoknock** [comment]
You're not sending screenshots of Xcode saying, "Build successful." That's all I'm asking for.

James 408-685-4049

On Sun, Sep 18, 2016 at 4:09 PM -0700, "Josh Baker" notifications@github.com wrote:

Sorry but I'm not sending screenshots of apps. 

If you are running into errors, please provide those errors and perhaps we can find a fix or a workaround. Thanks.

**Comment by theoknock** [comment]
Or, consider taking the same screenshot, but in Xcode (seeing as what you sent is clearly not Xcode 8...).

James 408-685-4049

On Sun, Sep 18, 2016 at 4:11 PM -0700, "James Bush" theoknock@gmail.com wrote:

You're not sending screenshots of Xcode saying, "Build successful." That's all I'm asking for.

James 408-685-4049

On Sun, Sep 18, 2016 at 4:09 PM -0700, "Josh Baker" notifications@github.com wrote:

Sorry but I'm not sending screenshots of apps. 

If you are running into errors, please provide those errors and perhaps we can find a fix or a workaround. Thanks.

**Comment by tidwall** [comment]
The screenshot that I attached is from Xcode Version 8.0 (8A218a). The Avios framework built successfully after I converted to Swift 2.3. I don't see how a screenshot saying so is needed.

**Comment by theoknock** [comment]
Because I don't think it builds or runs.

James 408-685-4049

On Sun, Sep 18, 2016 at 4:21 PM -0700, "Josh Baker" notifications@github.com wrote:

The screenshot that I attached is from Xcode Version 8.0 (8A218a). The Avios framework built successfully after I converted to Swift 2.3. I don't see how a screenshot saying so is needed.

**Comment by tidwall** [comment]
Sorry to sound like a broken record, but if you are running into an error please let me know.

**Comment by theoknock** [comment]
You're not being redundant; you're being evasive. If you cannot produce a simple screenshot that says, "Build successful," obviously, you're software doesn't build.

James 408-685-4049

On Sun, Sep 18, 2016 at 4:23 PM -0700, "Josh Baker" notifications@github.com wrote:

Sorry to sound like a broken record, but if you are running into an error please let me know.

**Comment by tidwall** [comment]
I see. For some reason you believe that I'm being dishonest.

I said it built, therefore it does. But successfully building on my machine is not important. What is important is why it does not work for you. If you do not want to provide error messages then it's impossible for me to fix the errors.

**Comment by theoknock** [comment]
I provided the error message on Github.

James 408-685-4049

On Sun, Sep 18, 2016 at 4:37 PM -0700, "Josh Baker" notifications@github.com wrote:

I see. For some reason you believe that I'm being dishonest.

I said it built, therefore it does. But successfully building on my machine is not important. What is important is why it does not work for you. If you do not want to provide error messages then it's impossible for me to fix the errors.

**Comment by theoknock** [comment]
You couldn't just have done this?

**Comment by tidwall** [comment]
Done what?
