### ISSUE TITLE
aac.h = File not found

### ISSUE THREAD

**Issue by theoknock** [tidwall/Avios#3]
/Users/jamesalanbush/Desktop/Avios-master/AviosTests/AviosTests-Bridging-Header.h:5:9: error: 'aac.h' file not found
# import "aac.h"

```
    ^
```

<unknown>:0: error: failed to import bridging header '/Users/jamesalanbush/Desktop/Avios-master/AviosTests/AviosTests-Bridging-Header.h'
/Users/jamesalanbush/Desktop/Avios-master/AviosTests/AviosTests-Bridging-Header.h:5:9: error: 'aac.h' file not found
# import "aac.h"

```
    ^
```

<unknown>:0: error: failed to import bridging header '/Users/jamesalanbush/Desktop/Avios-master/AviosTests/AviosTests-Bridging-Header.h'
/var/folders/wk/7xff2m190wqfqtf_hx1p6cy00000gn/T/AviosTests.swift-e417ac/AviosTests.swift:26:19: error: use of unresolved identifier 'aac_decoder_new'
        var aac = aac_decoder_new(44100, 2)
                  ^~~~~~~~~~~~~~~
/var/folders/wk/7xff2m190wqfqtf_hx1p6cy00000gn/T/AviosTests.swift-e417ac/AviosTests.swift:28:9: error: use of unresolved identifier 'aac_decoder_decode'
        aac_decoder_decode(aac, nil, 0)
        ^~~~~~~~~~~~~~~~~~
/var/folders/wk/7xff2m190wqfqtf_hx1p6cy00000gn/T/AviosTests.swift-e417ac/AviosTests.swift:29:9: error: use of unresolved identifier 'aac_decoder_delete'
        aac_decoder_delete(aac)
        ^~~~~~~~~~~~~~~~~~

**Comment by tidwall** [comment]
Thanks. The aac code is no longer needed. I just pushed an update.

**Comment by theoknock** [comment]
An updated...?

James 408-685-4049

On Sun, Sep 18, 2016 at 4:47 PM -0700, "Josh Baker" notifications@github.com wrote:

Thanks. The aac code is no longer needed. I just pushed an updated

**Comment by tidwall** [comment]
I corrected the sentence.

**Comment by theoknock** [comment]
Okay.
By the way—and, please, excuse my lack of education in this matter—how can I set up a trial of Avios that, for example, plays a video file on my iPhone? To what methods do I pass the data, etc.?
In other words, where's the in and out on this doohickey?

James 408-685-4049

On Sun, Sep 18, 2016 at 4:52 PM -0700, "Josh Baker" notifications@github.com wrote:

I corrected the sentence.

**Comment by tidwall** [comment]
No worries. I just updated the [README](https://github.com/tidwall/Avios) with some basic starter tips. I hope you find this info helpful.

**Comment by theoknock** [comment]
I have to be honest: these instructions suck. Do you have actual code?
Here's what I use to get raw file data? How would I plug this in to Avios?

-(void)openChannelWithURL {

```
NSString* filePath = [[(AVURLAsset *)[self.playerItem asset] URL] path];

__block dispatch_io_t channel = dispatch_io_create_with_path(
```

DISPATCH_IO_RANDOM,

```
                                                             [filePath
```

UTF8String],   // Convert to C-string

```
                                                             O_RDONLY,
          // Open for reading

                                                             0,
          // No extra flags
```

dispatch_get_main_queue(), ^(int error) {

```
                                                                 //
```

Cleanup code for normal channel operation.

```
                                                                 //
```

Assumes that dispatch_io_close was called elsewhere.

```
                                                                 if
```

(error == 0) {

channel = NULL;

```
                                                                 }

                                                             });

if (!channel)

    return;



// Get the file size.

__block NSNumber* theSize;

NSInteger fileSize = 0;



if ([[(AVURLAsset *)[self.playerItem asset] URL] getResourceValue:&theSize
```

forKey:NSURLFileSizeKey error:nil]) {

```
    fileSize = [theSize integerValue];

    NSLog(@"fileSize: %ld", fileSize);

}



// Break the file into 1024 size strings.

size_t chunkSize = 1048576;

off_t  currentOffset = 0;



for (currentOffset = 0; currentOffset < fileSize; currentOffset +=
```

chunkSize) {

```
    dispatch_io_read(channel, currentOffset, chunkSize,
```

dispatch_get_main_queue(), ^(bool done, dispatch_data_t data, int error) {

```
        if (error)

            return;


        const void *buffer = NULL;

        size_t size = 0;

        dispatch_data_t new_data_file = dispatch_data_create_map(data,
```

&buffer, &size);

```
        if(new_data_file) {


            // Build strings from the data.



            dispatch_data_apply(new_data_file, (dispatch_data_applier_t
```

)^(dispatch_data_t region, size_t offset, const void *buffer, size_t size){

```
                NSData *data  = [NSData dataWithBytes:buffer + offset
```

length:size];

```
                NSData *data2 = [NSData dataWithBytes:(char *)[data
```

bytes] length:size];

```
                return true;  // Keep processing if there is more data.

            });

        }

    });

}
```

}

**Comment by tidwall** [comment]
You will need to derive a solution based on the information provided in the README and source code.

The only thing Avios does is decode raw H264 frames. You cannot plug in an AVURLAsset stream into Avios. You must create an `H264Decoder` and call `decode` for passing each frame one by one.

There is only one main class [H264Decoder](https://github.com/tidwall/Avios/blob/master/Avios/H264.swift#L49).
You then call [decode](https://github.com/tidwall/Avios/blob/master/Avios/H264.swift#L234) for each frame.
The output is an [AviosImage](https://github.com/tidwall/Avios/blob/master/Avios/Avios.swift#L11). 

The output must then be handled by you.

**Comment by theoknock** [comment]
I was told that you just tested Avios on your end with such a solution. Can I see that?

James 408-685-4049

On Sun, Sep 18, 2016 at 6:17 PM -0700, "Josh Baker" notifications@github.com wrote:

You will need to derive a solution based on the information provided in the README and source code.

The only thing Avios does is decode raw H264 frames. You cannot plug in an AVURLAsset stream into Avios. You must create an H264Decoder and call decode for passing each frame one by one.

There is only one main class H264Decoder.

You then call decode for each frame.

The output is an AviosImage. 

The output must then be handled by you.

**Comment by tidwall** [comment]
You are mistaken. I did not write a solution nor did I say that I did. I simply verified that the framework would build in Xcode 8 with Swift 2.3.

You will need to write your own code base on the information I provided.

**Comment by theoknock** [comment]
I'll let my sources know. Still, I'd like to see this work.
James 408-685-4049

On Sun, Sep 18, 2016 at 6:28 PM -0700, "Josh Baker" notifications@github.com wrote:

You are mistaken. I did not write a solution nor did I say that I did. I simply verified that the framework would build in Xcode 8 with Swift 2.3.

You will need to write your own code base on the information I provided.

**Comment by tidwall** [comment]
OK and good luck.

**Comment by theoknock** [comment]
So, can you provide something very simple?

James 408-685-4049

On Sun, Sep 18, 2016 at 6:30 PM -0700, "Josh Baker" notifications@github.com wrote:

OK and good luck.
