### ISSUE TITLE
Build successful only after deleting test unit

### ISSUE THREAD

**Issue by theoknock** [tidwall/Avios#4]
![screen shot 2016-09-18 at 4 41 59 pm](https://cloud.githubusercontent.com/assets/1622579/18620021/f8631448-7dbe-11e6-83c1-43f7c42bedc5.png)

**Comment by theoknock** [comment]
To (at least) successfully build this app, you must:
1. delete the unit test target
2. convert to Swift 2.3 — not 3.0

**Comment by tidwall** [comment]
OK. Please pull the latest push that I made to master. It removes the code that is causing the error.
