### ISSUE TITLE
Parse and extract frame

### ISSUE THREAD

**Issue by Ramshandilya** [tidwall/Avios#5]
Hi, Can you elaborate as to what you mean by -
> It is your responsibility to **parse the stream and extract the frames**. The Avios decoder only cares about the raw frames. A H264 frame is also called a NALU.

I have a H264 stream which I'm trying to save it as MP4 file.

**Comment by tidwall** [comment]
Hi, 

This means that Avios only handles the H264 frames individually. So you would need to provide a parser for your H264 stream that reads each frame and sends one-by-one to Avios. Then Avios will produce images that you can display on the device for realtime playback.

**Comment by Ramshandilya** [comment]
Firstly, much thanks for the quick reply. 
I might need further clarifications.
It looks like `func decode()` in `H264.swift`it is creating `NALU` from the data fed.
And from what I've read, H264 stream consists of series of `NALU` (where the NALU may contain the frame or the SPS/PPS).

So what kind of parsing are we talking about here? I've to breakdown the received data into individual NALU and feed it to `func decode()`?

**Comment by tidwall** [comment]
> So what kind of parsing are we talking about here?

When I say parsing I mean reading frames from a video stream.

> I've to breakdown the received data into individual NALU and feed it to func decode()?

Yes, `decode()` accepts a single raw NALU frame as bytes.

**Comment by Ramshandilya** [comment]
Thank you :)

**Comment by tidwall** [comment]
You’re welcome. :)
