### ISSUE TITLE
Undefined NALU Type

### ISSUE THREAD

**Issue by betulguleryuz** [tidwall/Avios#6]
Hello,
I am trying to decode the h264 data frame-by-frame and using GCDAsyncUdpSocket library and getting h264 data from Udp Socket. I have gotten "Undefined nalu type". What's wrong? Is the format of h264 frame correct?
Thank you for your help.
I am using your library like this:
in viewdidload method:
h264Decode = try H264Decoder()
than in udp socket receive method:
aviosImage = try h264Decode.decode(data: videoData)
Example:
The h264 frame : [UInt8] type
00000001419AC180BD736A8C72E2E5ED0E337D595C5464F2D46F7B8314A066358BE6C7AEF5CDD104D86D0FC55A407246548832D7E1D960F26C91578FA448F5B76BEBE925F84A9BF319AF898653473E7CBD5589E464B27E743D93191C5AFC4DA2574A5826C096F9C9320E682E5959CE69F3725CDC27AC627333464E3E1784CF87FB196301AFCC183F84ED8658D34F7D4B1FC5C8FA0D719C32FCD31C690D05E5A493456F8CE5B416E498C655399366A9D157421A1E7E37B645DCDAAE130CE6346C1014D7B261C75106BE78B2FCA08FE3681479BA066A06528D75764681B6153713A647AFD8FBC57E2F8CE7E6C30F78BE44A9E580635DF17D7CB84641D35CD6419669617E696EC6FE69E23767F8B85B79942E1B18F5B3D0FC5C3E9EEAFB9A7498711449E2A4F4CBC747642F34F63666123C1C759782FA0CD7EBD09AC6BFE2545CB5275F6680BF11841C5521FCB7F1798404ECB90A684C77B4ADF2CE58E96437E6C951C397E7934419D393B6D7309C70DCB61BAE497DC70E60F8AEBDF0B4BC1634B52E791F35FA7F8CF1D906A1DFE1F749344DDA63A290E75D27363556A3358FC738C57912B8DBA1C383462F2D163CFEA15E3849CB2A338C60D7E8BF194025635B0DBDF538C1DA7D64B86B69335E32BFC2B29890C70678E7DF590CFFE3F467DB37C174775F26792372757D317A33FDF4926A6177634DB3E6BF88C9BB77FC31CC946A06F576ABF2FEC7A9F08D48CF2B0A46780708F13F08D91E87535DAA74FE8325ECC38AA523278BE5B33F68B1F095C534821E1F32556CF337CD0D93C9DF167E14F3DC6EEA3C68B178FDCE68B3F0F8CC1C690D069806C0DD46468DB1B640EDE65A0A742FC25C3D80F0FE06A76EB0CB494A470AA12FFCA6D319A9A1FF131FB1BD2E01E5E93628BE7EFBE57A42796F7F8AA4B4F1C6ED704778D0C5FBE5918439E3E3BC623EEB6567846893F34BB3CD8BDE77AFE2E879B4CA93D8BC212243B09F8DDD835A9E5E17E4F4E5355FECFCDA086E5FE11C9B6855ED63BFFC21EC43682D50C3A4A9437819E1DB1B48622D885808183EF5C030EB06C65420BEAD7EC2FDFAD245E481FC703919812355BC2D497C5C1F98E3078E105E716C1FFE2E6108E0E34070B22ECA1788CE7D2AADC12B7BBF84B97DA8276ABC854A98B871D242D67A15AFFD3E3A49E891079F3D0647C671FDC8D7AD83D0F7FC7E1D5AC756597C79F2FCC6FC3922681123AFA3D0178576107220FB11C9FEA8BFAE0BEADF41A607D617D2E853B98FBB5512221C7E44BC7F037115F558ACF7BA1B1FC23D84562B4C9BE1AAEE2F0454318BB836F936C8C7E09A6551CD363831938B675F09D0CAB3C1C27DEA79F1B95846A063CB1316D9F0B6347735E51362D451845CDE5CFE98BFAFC6DB60F30F9396148C340F6C22BD03986DF40BB4D215FE9F853355C87632B13DA341A695E8A39BE9281E7E1F1BACD28569E78880B1F890769F3824B58383AFD8150BC6C393CAF39B1D96383EC8B4104DC105F001EDD5FBB7F53061EFEDFA1F4F8DE1C4F3561620DE89749A5B31E2D3B0547A39F5FED78CA2B8501503DCC899C11D99995A7740E35F11B20D6BF70624369DEFF19F1E49DA89BBE63F981126EE3BFEC81BD5F55C117E11A8C04067D7A31C8F72375D7CF4F8627488120CB7875122D53FFE58D18BBF8D95D06482980B341293B620B0F8D8EF217C0458ED709A24BFDBF1B3D19111B14D69ABB2840C79DD911725278A80A3D1FD88799B70E6BC097F6BE3BC08C6604538F2D67B69A5ED9E4E0836454906D8D8C56B7CD6689525D3FF87E71B12BFC8E9C136CF92A121A2EDFED786F2ED76BEBECE37176E5CD9323C7C10D72E9E5A9852DF5AACC276DB2B03A88C6ECA90A89043CB8C4EDB1B21A9B6EC7E58CC21BFD5E10855C3D9AF2A21C2AFD7BF84ACCE22A9EE4A20EA5FB0C2F4BFC44A503BFD7B5F6935847D77609665A3F257E746C9BC4BC45A6D2BD4EE0FBE4C2919BD3E119EC74761449666C438328EDEA37AED8B83185E32F4A6AFEC9EB44E6E6FCCD3C60695DAD27C1A8E0104DAD2D7961F0A762043A5AFD503E1A5F7CA34326E403FB8DA5EE0A9AE84E09B71D41C6BED115F6ECF50C7E2A317B237CE734DADC1E194BD1581A1F053DBB46D7646AC23237EEC26FBC32A1479B821C3C8A71EDF19090CEEBE018D72F20E20FC70D69D168BBDD8FDB178D9E2874EDD32080EE0DD1A3E4DB87067BB06BFB39396A96238BED97B6FEC83A29DBBE9A51933286F220E996046B773248E47F826D06E74E86E0DC4D4ACF820C01EF774F91DD0E7725BCDF75FB5EDFC5C9F40F1ABBBD5EEB82AC01A8EB3F8765C6F37B08706AA367C2358E822A264AEB524C33498860FC274B39A44E480EDE5E71DA09738ABDF7F112A21D57866BBFAA6AEE27931865BF7F05F718DB61975A10B00E9A4BBE7E2FFEC3DB13D4A4F4824D06F44B708E4B362899452AEBF08DD2B7194C6DBFF73A8FCCF3FD9E5620FD84BF04FCAC03F7A6C7A50361E4EEDE4BB8EE8CF5CB3BDB1EC411F938E0CE5515F89AC39D4C46D831B245E09FA0A60DC5E31475C5831D0885A5EA19F17D86E9D319188DCA131E2F843B0CCBB101F29D810753756882FF8C8EA05032351D08669C7E2B96B88910D38289C595AF480934F0FAEFCB67B3487577DDA11709DE99984D668EE0B2E791DB4A838EC9933B8F0614DA658266C65E8C4775AFF4FC334C35AFC791F01AFF75CF7F41FD18FFC2DF194C959AB5D97CDC5C2362CDC096A470F4EC7F8DB31A73365025E32C284C08E9D81E1BE849CBA5B7EFFB811B727FABE96AB19EB803F086907FAEACA39ADD466427628D24CDF9450FF8623EC2632D1656179371F2ABF2DBA844A4B843A32E719ED58815A4B37C9C699D698FE23CB78FB61BFA778BAA187DFD798DF4AE3A18526BE3DC3302A8385EEF9A70347F0F487E350EEDD2E67DA429898788178487ADA7D7E817E32853CED41A550909F782FB63AB5AC91210FC3780635CEF6A3EEB588B9B763225F0613A85E3A99E5423CE2418260FC5FEC7EEC61238DCA1640013D736D479CBC2B97238663475AC33D7E85F873B185DBCBFDBF17CA7CBB2421CBDE2E04CF7A6FF8C4EB21DF3797F8CF358ED8846F8652E4381845AC859FDF7CB229A8E99F8ABAD1218DC519AD8396AEFF88A6EC28C316A07534278A984912265653FF0ECC20476E934FF51AA0CCF1444F88A4C6563F97EBAEAC7C6C9F2E9998DF9A16B8E0D083FAE50DA6ACA315932D7C12A3113FCC93F9673E3B792B59FEAF114C27B4E821FB5889A6FF1D835F0103DF5E8DFFFDF4205AB10FF9A5A0A9FE4D341842C543FC10C303F2BDFF5F378D9DF8208FCE26AE51D63077D33325691B7B99ADF5F40BF87BD024A1262950C09CED45A181A749A230D7FDDA94491AFF605590A12D0D86125947B4E818D43F978F93309709612390C1D90DF98BC65C69677EDBD532653E9FE5B70EF0AFC6E0A766E5F94E90F169A18F0B811A38BC01327C3D7F43F846C2944236509ED0643D42A549808643178B945468E7A1704FEB4226E4F8CA44F109CC746243805B5EB367807C52BAB823DC92EB5C5D271EB563A1691CA6ECDD5AF6B6EBD1AFA2EF87B137E35F1DC43E3D5A358861F94EFB51325FE83F0877894CE642459F7A0AD993D0A72B0BAF4BC104A0B9A458C6D1B660E4B28D75E5733AFF47E13B4DBF40CA41040F5CEDA4BAB3B8BE1C4D68F3B68A81055A0EAF08C3F08455AAF55DED6C317BF9FCFD1578F905A1ADB8F18D2C20A442FAC7E3A99FD5F8298F4C550332AD1A5E123A244C40DAA46FF08E38FD047A30BF0636E16A5C1DE3EC31ECFAAC7DF38059223B6FC3CE6D2F49B45D8C0776FCD44B89A6C47C96D5AAE11952CC8B61C32B360CC9695F8CB5F10E1AB42520D049BF7AA3698AE37BDBEE639430493F1D545128106B627CF9A818A8C853BDDAD2C0D5F934DBA7F88AEBD417F0CCB83A1E137AE784268EF3FF12AD08336FB0CCA4647C1618BCCAE5A3290910E4E3B8AB40C37AC89B3D915210EFD8EB6D1E34CE3C184EC7C7FFFF19645EF87DCD0E43470EA706AFEBA399398DFA0701960F930EF53A2F084AB1CBDB06D968C0DD1336EC468BCF5FD8162095F2ED54DC2B982FFA4DA12B136F636BFB02D6DFC6C32DBDEC93A8D84C84986E8D26B101044EE351604EC321BC60EFD7D8F4BC3B1E346E33465AA3D4CCC2855F5F44B847B8F9C346E586E3266A28B52479C78CFFC104B41EA86E1D810D1A18276F343F4A149AFDFF08DA81AAD62D10A3499962D49C2AE81A394470BC4D2DFF2324C04AE46AAE7D2F7B1969BE6F0EE08F8529EFA0864963C585C1872BCC8950EBB149B53632D21B6612FAEF8EB21F25056EE6AFD88160D3F8094D0CD33E1E0830D2504029AF4EA9CB8F51A2A4951C6B3B5DF8FEA735F5FE2788EBD583A32410C43C9D53D73777F24BFA2F1936150B4C5D3087B92F490F16904E66557FA381221989F1D3D69DBA23492A4B495519FBEE586BEB55683D9589E5968826EF5FA0FF11329331E7E96B8AB71A1319546834BC155818CE8C23533FD590EE3067C3199E3E1E5F1D335C7470D98612F96BCC3449CC3D524BF96309307C4F2610B3C634D705541A23206553B38692E8A7CF8DF05F66CE3B6A32C2144BFA1FC559A9A15072B69D5F0D92F0A74DA332535EA7423A1D3BB6D6474D53B0097C7746693123197373C95596B1D03549BE12A464CB5C621A1C1BFB9D0EAB84397CCB8F020C12FAE32CCC39899FD96881ACCC466A30A15A7CA4BF0F51267C2397F442B17C32ED752F6FFC76F566D119191140C44278DBB945FD51E2FC3D54F961BA6C9FA0C16EBCDBDF423EA1B78C6BF65F89A3D5C28C647496B455B1F35E912BF0ED58F981E646CADD6361B1B6D7D17F5AE99B56BE6E56019EEB4CE9FC21184FA547618D9A68D2FD6F866F22AB1B0DC9D68251A918256E0F71B6274948E08AB1D802FF5AE396BE0AB6E5A30AC10210B87535F364AC62BFC4C644DFBE27B7728AE5E4C65A1FF09DE22ACDB1D1C2E39BF8F8D18858D479A553850332A6868670BC4D741FA58492390C9F2DA0CF68FAD5C74BFA1FC23F66484CF7D50D540A124E3AEF78C86156B726C6A481A76F8A095882D552BEEAA519B2C374D626DC62DE907AEB98FFC21D98693387ADD7AFBEA8621B4E206D3EA9E37B23BE415733EFE4A3FE66A13AEFFA7BB6CD7F4B49A419DAB9D65ADF0649BABFA0EB8AC3A91999E7AC543E51051F89F1B2836547357C1548647A14B2F8D135A755DD8FF7C6E22A933675CEB00FD5348601ABE4F26B1E91E32A4F0E7AFA02FE1BB77906BFD531AF3D7FA7E4999210DBF191C367C4C48E63DA749E9570CE6AC8657E8FF71A145C3AE7AD3FFC12C1DADAAA6E324DF55C155841F4072950D1DA5C0D32C2F4548D303D1FD7C211FB903ADAA4AC332138B24B462501F8463D52A18FA3CE323A6996AD53F842B0DEE4AB25B19147C4A5393BB3E93D8DD75EAEF9724E1AC7623AB5FC9C5470E59CC0C28740D8702ED94D9FC6CDF54F8E81C5EE34C3E4D6303E5FEAD22CD7D7D3E3289A41AB0635359F64377D2C0C18D63C6604067F1905145F5D7CF43FDF7CB83C5C3E11B6571841591C3E3DA919E83585D1B27F11A165A51989E0EB49F57F86332F76E57D7FB2F09F4C9273C7B8577241D132F084F1AA9249DC7AE6C97C4C54A88C31638555DED56ADA35298CB3D5C905BC1B84BBD71B8C9CE0F3A5438910F9BC7711D19D7D7AF93AF577A4927E1C8FC2612E8DB5FE9782A94C5B51CA8A63548213BA07AA380525C77561E10AB3640CAFA15672699537EDF36D324EFAF575E9788D5E60E163F9B8CF6B88E12779CF5908F65E3E8994F75665325D7C441DAAFCCB882AB83DCDC2362450DA9F4AD41A049F60A33BBC96C7ACFEC4EB8F1DF4A3A78FC1465FB0E1456B97CD48AA35CD9E51E9AF04707F9FDF5EAEF0904D8CC41F929FB1535EE41E1A98CC36ABAFFC271E08051A570735486C98214DC180F5156AF8AC369EFAC4AAB39C03F2E3B10D466A18F1F8E6B0DD760FFE2E6388E8C8858569234726B9BCBEB9474BFEC45F530E5720D717B6864ECB51E9E0BF6ADEDB1990AF7FF0E50CD76976BFE1CCF143A4BD2FA649835BD84AB8AD7F629DFC256F1C417B42743E8AE98CDDB6B2A0E2894CDB25B7BB1319143B7090AB786C8207D6A6E6C3799BF8C8CB94025AC5A340CF11B359BF719B7F5ADE4A403B0F3A974AF84ACDDB667886B4CD7E22DAB72D0763977FAB9F1F0106BE7EEEEDB736D700DD78B3D5915BD7EC3B280F0FCB736F44541E4DD219AFB0B54AB35886361C690F8BD3FF0CC20E9F405D507FFC35BA2635F61FF0B53A72B913831BAD2FD2AB061A7733830FC92C66B5FBF85686B329194FEAAFEB5C934743F171D0107C7463DB9F0D513BBAFD713CD634D3D74266A50DB3A4B71994514EC1A594A2E1F208570978F1CBDA20CF4825B46A40DEFF17D99F19176A8BCBB0DD3F27083DF5FE1DF99E03BFFA821D16D5B051C0F5A34A82D7AD7F20D7C3104BFB51B121763BEEEE1025BC2AD85FF96D95432FCF5DAFF8725C65F7BFE97C12796EBE09E5EB23746EBB0F1369CD438711BDA0528E41FAEBEB55C5511703FB62D3352A2D8FC211F817492B0923C74086747CDC7E2FE08B8E69F5A6B0DF87929CEF2622FCE2A872A464761719A545D1B8EE288BD7AB92631A3311F2E636FF8BDA262B881ADBC6357E2F56A8325FEE8924671A2F54D5C9181C1C1FC1043ADABAA344AE0A1C8EB6B3ADF7F53B4E54EDFCD68892DF936D99E0B821D2AD7DE0FA4BD52414C6AF75634EC7EF3B691D1C5C305E1FB2C3A9767C8766797419CEE872BFD48389BDF13D29981949A70B4CD41C9FCAA50D7DFD2B827E652C6F9D9CF9E88E4AC8A7B44DB637F36499332F3D7D177CD6DD2F842B6D87432A5890D3621B42F04D329665695C34F15B72FAEBE48E67F270519DB46DD93F72944EAC33E0E356B1A64E6C38BD4FF05D1BCA390E25E302BB859A9AC9144C2842DF2F241FC12784FEABC3D82594E1F748B69A774787C27D865C77952F96CB13AEEFB64EEDBD79FD8471E37376DB21CCCB9318F24FDE2347AD3EFF9B0774B0D5D357416919473CD1A36D072D3EB27714A1AFEBF2CDA653BC7D75EF822C7E71FEFBF3EBD1E6FD5AB820D0940E50779FB32C06EEA98D6B3AFA3FE0C33B41DCCDC492FA0BFABAF87ED4AC110D360CDA87635B5F61FF0451938729971C91B665F74172D170512C27579214DA6E4C92412F7E6C86A1A03708D9B9D5610A3DBE0E3287012FD798EE96FAB74F5CBE4A4BF8EF8BF3DE48B5E11D266D148253555BAD535D7B87C5D36BB1FC84A580F1DF89E990BE953F042F1748E971975ADDBE4A1BE95B2FD43BA7846DEF8EC9021D5F23BC216A3C7DA0BD3DD07701F75C1E2D09D69899D9C26CE7BE7AE97F725596F972469AE7AEACBFD62FAEBE7BF47FF3632BFC5D6C67EED570F5119FC250E4AE90EF49EC3FFE3A04EFE6E177F4DE9B52EDD4D8D75991DBB57E69DA3E4DD3D4317111323C64E50336B085D2EFDBFC254104AFC4F788ABCDFB5F3D53FFE09377E5F0CDD38CA615AFFE0921D71FCD1E93979F3E1DA22D2564D1E67CA89E35F40BD7846185BC6E78C9DDD1CA680E37B5B5DB0EFA608A398E041F66B549EC90E4CE46ADE5BB092E2273174E9189AE2CE2FC335710FDEBF6FF05D7D69B3F3677DD3CDBE17A44758D8DEEBDB605FC6C89E1A1FECDE85B1D83F61B51A34889E9C851F2FAB63ABC6B88C5FC38F965F876E52B6B85E340B43373D8C89ADFE7AFD8DD817820F365995AA49C39534DF5D2FF8B9E9948B7847B2724FF9133CDF5397CF5B0B4BED9EBA3FF82FE5D4AB754D7FF3D894C761FF8663177EEE9FFCF8341DBF7D5FE49A19AD70450E5AD2AC6EFCBE5A49CCC139A57C32FBF094F9DEFF1543306632769EEBE23C8FA0BC625AF899288A9CF591F5D7BEAF7C4CF1298F1EF7F0EE8CE82C8BA0EDEA4101A04496DD7ECBF11D841654C8F6C38D78AEE6FFC33C3FE8CB54FFF931D806AF27758A27E7AF4BDF0E54D2FBDBF7CF8AD7FF3D7B5FE78FBD97FAE55CFEA497F477D73D6FFAE08769717CFD767FF0DEF75D17FA3D5FFF86F8AEAFFFCF7FF434A99014D19E33515A0FC7605ADD563097B7388717F0491EC401291A51DFAEBE0AF6CAA684B30D39D4B3E91DB1F87C218FE9686D3B085BD508669D63771EBEFB4487B95894C7E08B9A8B149CB15FF3F2A5FFDF8CD2C7F05F1CABEE5AD35EBF78EBBEBE19F3EAA7FFCFEBFFF3D692A2FF7AAFD62F9EB6089FF5D65F3D74BE915B609280CB04ADCFAA515DE1F9391C05FFF25E9F682949B3E41B9A3042DA8E92107668B3262CEE9B9B829AB68D63784767085E2B0F75AB4DD8639A8A81D0F00FBFC5E1EC6274C7D59B67185634362548BF5DAE97DC546C37F60BE12E27E7DAB91E222021B1AD8CD7C25F607F5FAF5F597CF5AFFE7AB5FFD65F3D6935F5CF5ED7FAF5736466FE7AA7FFC3597756ABF5D4E95CFEB7FD70E577AF6BFD6FF3D74BEB8479BA266338C016F75C27D0430771EDFF09CB9439E0CFF1B1BBBB2A5311EAAD22CC5DA731A4FA6273D7E83FC29DB25DCB7865A97590F17EF8B9A76106BDABC98DDCD58117B2C3847D78BB22884531AA447ECF2A52A2E2FC12E86CC108F47536629B8C3B0DA1311C08DF17B043318BEBF7C2F1C4133677DAA9C23232C776199B0FB5C07AC8D53EC3F134B2401D9DC124F9EB4BF43896BBEB17D62AEBABEB52753D5C391DF7D6FFAE7AA5FFCFAF4FE11CC20CADFF5D6BE08AF6CFC8D252E688CD9483EB31E6317E23E3374A5B468D4D1B7E3FB90407ECA2ADA0F462C377F8DDFD09F351ACD4694913C086B454CC69BED7E096A880D7FE5F1C1F434B40FE97EF2F45BEBAF8537216F44832B34A08B79F45D1F7AE5AB50B74C7AE3C47DAFA5827FFAD7D4CBF925CEBAE58953C970471D33FCBE7C5BFE4E09376B55CF56D3FFC2B2E75D35A5FF8563D2BE767553EB68BEB821969E5F0E6D557BFF9EB6FF7C969F5D5F

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
@betulguleryuz 

Yes your frame header is all messed up

Firstline:
`00000001419AC180BD736A8C72E2E5ED0E337D595C5464F2D46F7B8314A066358BE6C7AEF5CDD10`

Learn the different formats of h264, lots of decoders work different ways. For example, take the first 10 bytes:



### Annex-B Header:
```
[0] = 0
[1] = 0
[2] = 1
```
So the first 10 bytes would look like this:
```
001419AC18
```

Now get this there's some annex b that does it like this

### Annex-B Header:
```
[0] = 0
[1] = 0
[2] = 0
[3] = 1
```
So the first 10 bytes would look like this:
```
0001419AC1
```

Not sure why, haven't looked too far into it I just have code tricks around it. 


### Avvc Header: `<---- The format you need for iOS VTDec`

The first **4** bytes are a big endian `UInt32` size of the frame _without the 001/0001 bytes header_


### avcc Header:
```
[0..3] = that size mess
```

the first 10 bytes:
```
[sizemess]419AC1
```

**Comment by tidwall** [comment]
This issue looks resolved by @DogFive. Please feel free to reopen if needed. Thanks.
